name: list_utilities
description: >-
  A collection of basic extension methods for Iterables, Lists, and Sets;
  and, a base class for higher-level implementations of List.
version: 1.0.3
homepage: https://github.com/james-alex/list_utilities

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  collection: ^1.16.0
  lints: ^2.0.0
  test: ^1.21.4
