name: list_utilities
description: A collection of basic extension methods for Iterables, Lists, and Sets.
version: 0.1.0
homepage: https://github.com/james-alex/list_utilities

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  collection: ^1.14.13
  pedantic: ^1.9.2
  test: ^1.15.7
