name: list_utilities
description: A collection of basic extension methods for Iterables, Lists, and Sets.
version: 1.0.1
homepage: https://github.com/james-alex/list_utilities

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  collection: ^1.15.0
  pedantic: ^1.11.0
  test: ^1.16.8
